### Lecture 1 - Exercises
---

1\. Import the Numpy package, and give it the alias 'np'.

In [1]:
import numpy as np

2\. Create an `ndarray` with 10 elements, called `a`. Its third element should be 1, and all the other elements 0.

In [2]:
a = np.zeros(10)
a[2] = 1
a

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

3\. Add 3 to the seventh element of `a`.

In [3]:
a[6] += 3
a

array([0., 0., 1., 0., 0., 0., 3., 0., 0., 0.])

4\. Change all the elements with even indexes to -10.

In [4]:
a[::2] = -10
a

array([-10.,   0., -10.,   0., -10.,   0., -10.,   0., -10.,   0.])

5\. Convert the `ndarray` `b` to a list:

In [5]:
a.tolist()

[-10.0, 0.0, -10.0, 0.0, -10.0, 0.0, -10.0, 0.0, -10.0, 0.0]

6\. Create a 3x4 `ndarray`, called `m` (initialize the elements to your will).

In [6]:
m = np.ndarray((3,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

7\. Index the second row of `m`.

In [8]:
m[1]

array([0., 0., 0., 0.])

8\. Index the third column of `m`.

In [9]:
m[:,2]

array([0., 0., 0.])

9\. Create a 3x3x3 `ndarray`, call it `M` (initialize the elements to your will).

In [13]:
M = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],

              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]],

              [[19, 20, 21],
               [22, 23, 24],
               [25, 26, 27]]])

print(M)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


10\. Index the second 3x3 submatrix (i.e. index the second element in the first dimension).

In [19]:
M[1,:,:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])