### L2 - Exercises
---

1\. Create a 3x3 `ndarray` where each element is equal to its index, call it `a`.

In [1]:
import numpy as np

a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2\. Flatten `a`.

In [2]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

3\. Transpose `a`.

In [3]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

4\. Create a 3x5 `ndarray` filled with 7's, call it `b`.

In [4]:
b = np.ones((3,5))*7
b

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

5\. Compute the average of the product between `a` and `b`.

In [7]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [9]:
product = np.dot(a, b)
average_product = np.mean(product)
average_product

84.0

6\. Create a copy of `a`, call it `A`.

In [11]:
A = a.copy()
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7\. Offset the elements of `A` so that `np.mean(A)` is equal to zero.

In [14]:
mean_A = np.mean(A)
mean_A

4.0

In [16]:
A -= int(mean_A)
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])