### L3 - Exercises
---

1\. Create the following matrix as an `ndarray`:
$\begin{bmatrix}
-2 & -1.5 & 1\\ 
-0.5 & 0 & 0.5\\ 
1 & 1.5 & 2
\end{bmatrix}$, call it `a`.

In [5]:
import numpy as np

a = np.array([[-2, -1.5, 1],[-0.5, 0, 0.5],[1, 1.5, 2]], dtype=float)
a

array([[-2. , -1.5,  1. ],
       [-0.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ]])

2\. Change all elements of `a` which are smaller than zero to three times their values.

In [6]:
a[a<0] *= 3
a

array([[-6. , -4.5,  1. ],
       [-1.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ]])

3\. Create the following matrix as an `ndarray`:
$\begin{bmatrix}
-4 & -3 & -2 & -1\\ 
0 & 1 & 2 & 3\\ 
4 & 5 & 6 & 7
\end{bmatrix}$, call it `b`.

In [10]:
b = np.array([[-4, -3, -2, -1],[0, 1, 2, 3],[4, 5, 6, 7]], dtype=float)
b

array([[-4., -3., -2., -1.],
       [ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.]])

4\. Change all elements of `b` that are also contained in `a` to their squares. 

*Hint*: take a look at [this method](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isin.html).

In [11]:
a

array([[-6. , -4.5,  1. ],
       [-1.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ]])

In [12]:
np.isin(b,a)

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [13]:
b[np.isin(b,a)] **= 2
b

array([[-4., -3., -2., -1.],
       [ 0.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.]])