### L4 - Exercises
---

1\. Generate a 4x3x2 `ndarray` with random integer elements, between -10 and 10. Call it `a`.

In [1]:
import numpy as np

a = np.random.randint(-10, 11, (4, 3, 2))
a

array([[[  6,   2],
        [ -7,  -6],
        [  3,   5]],

       [[ -6,   7],
        [  0,   4],
        [ 10,   4]],

       [[ -1,  -6],
        [  1,   4],
        [ -7,  -6]],

       [[-10,   8],
        [  6,  -8],
        [ -9,  -6]]])

2\. Choose 5 elements in `a` randomly and change them to 0.

*Hint*: Take a look at [this](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat).

In [2]:
indices_to_change = np.random.choice(a.size, 5, replace=False)
indices_to_change

array([18,  8,  1,  0, 23])

In [3]:
a.flat[indices_to_change] = 0
a

array([[[ 0,  0],
        [-7, -6],
        [ 3,  5]],

       [[-6,  7],
        [ 0,  4],
        [10,  4]],

       [[-1, -6],
        [ 1,  4],
        [-7, -6]],

       [[ 0,  8],
        [ 6, -8],
        [-9,  0]]])

3\. Transform the operation described in step 2 into a function, that takes an `ndarray` as input and changes 5 random elements to zero.

In [4]:
def change_elements(a):

    indices_to_change = np.random.choice(a.size, 5, replace=False)
    a.flat[indices_to_change] = 0

    return a

4\. Starting from a fresh random array computed in problem 1 (i.e. re-run your solution to problem 1), apply the function you implemented repeatedly until all elements have been turned to zero. How many applications were necessary?

*Hint*: [1](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_equal.html).

In [5]:
a = np.random.randint(-10, 11, (4, 3, 2))

def all_zeros_count(a):
    count = 0
    while not (np.array_equal(a, np.zeros((4,3,2), dtype=int), equal_nan=False)):
        a = change_elements(a)
        count += 1

    return count

counts = all_zeros_count(a)
counts

17

5\. Approximate the expected number of times you would have to apply the function in step 3 to an array created in step 1 so as to end up with an array filled with zeros.

In [6]:
sum = 0
average_count = 0

for i in range(50):
    a = np.random.randint(-10, 11, (4, 3, 2))
    counts = all_zeros_count(a)
    # print(counts)
    sum += counts


average_count = sum / 50
average_count

16.18

6\. Create a 2x3x2 `ndarray` with elements sampled from a multivariate normal distribution with parameters mean $=[1,2,3,4]$, and covariance $\begin{bmatrix}
1 & -1 & 1\\ 
-1 & 1 & -1\\ 
1 & -1 & 1
\end{bmatrix}$. Make sure that whenever this cell is re-run, you still get the same matrix.

In [17]:
# Set the seed to get reproducible results
np.random.seed(42)

mean = np.array([1, 2, 3])
covariance = np.array([[1, -1, 1],
                       [-1, 1, -1],
                       [1, -1, 1]])

a = np.random.multivariate_normal(mean, covariance, (2, 3, 2))

print(a.shape)
print(a)

(2, 3, 2, 3)
[[[[ 0.50328585  2.49671415  2.50328585]
   [-0.52302986  3.52302986  1.47697014]]

  [[-0.57921282  3.57921281  1.42078719]
   [ 0.45743996  2.54256004  2.45743996]]

  [[ 0.75803774  2.24196228  2.75803772]
   [ 1.56228753  1.43771247  3.56228753]]]


 [[[ 1.90802408  1.09197593  3.90802407]
   [ 1.2257763   1.7742237   3.2257763 ]]

  [[ 1.54438272  1.45561728  3.54438272]
   [ 0.62430198  2.37569802  2.62430198]]

  [[ 1.6017066   1.39829338  3.60170662]
   [ 2.05771093  0.94228907  4.05771093]]]]
